/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PocoesRouteImport } from './routes/pocoes'
import { Route as MonteSeuKitRouteImport } from './routes/monte-seu-kit'
import { Route as ManutencaoRouteImport } from './routes/manutencao'
import { Route as KitsRouteImport } from './routes/kits'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiAuditManualRouteImport } from './routes/api/audit-manual'
import { Route as AdminProdutosRouteImport } from './routes/admin/produtos'
import { Route as AdminPedidosRouteImport } from './routes/admin/pedidos'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminKitsRouteImport } from './routes/admin/kits'
import { Route as AdminJornadaRouteImport } from './routes/admin/jornada'
import { Route as AdminDestaquesRouteImport } from './routes/admin/destaques'
import { Route as AdminDepoimentosRouteImport } from './routes/admin/depoimentos'
import { Route as AdminBackupRouteImport } from './routes/admin/backup'
import { Route as ApiPublicHooksStockZeroRouteImport } from './routes/api/public/hooks/stock-zero'
import { Route as ApiPublicIntegrationGerenciappPaymentRouteImport } from './routes/api/public/integration/gerenciapp/payment'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PocoesRoute = PocoesRouteImport.update({
  id: '/pocoes',
  path: '/pocoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MonteSeuKitRoute = MonteSeuKitRouteImport.update({
  id: '/monte-seu-kit',
  path: '/monte-seu-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const ManutencaoRoute = ManutencaoRouteImport.update({
  id: '/manutencao',
  path: '/manutencao',
  getParentRoute: () => rootRouteImport,
} as any)
const KitsRoute = KitsRouteImport.update({
  id: '/kits',
  path: '/kits',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuditManualRoute = ApiAuditManualRouteImport.update({
  id: '/api/audit-manual',
  path: '/api/audit-manual',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/admin/produtos',
  path: '/admin/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/admin/pedidos',
  path: '/admin/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKitsRoute = AdminKitsRouteImport.update({
  id: '/admin/kits',
  path: '/admin/kits',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJornadaRoute = AdminJornadaRouteImport.update({
  id: '/admin/jornada',
  path: '/admin/jornada',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDestaquesRoute = AdminDestaquesRouteImport.update({
  id: '/admin/destaques',
  path: '/admin/destaques',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDepoimentosRoute = AdminDepoimentosRouteImport.update({
  id: '/admin/depoimentos',
  path: '/admin/depoimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBackupRoute = AdminBackupRouteImport.update({
  id: '/admin/backup',
  path: '/admin/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksStockZeroRoute = ApiPublicHooksStockZeroRouteImport.update({
  id: '/api/public/hooks/stock-zero',
  path: '/api/public/hooks/stock-zero',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIntegrationGerenciappPaymentRoute =
  ApiPublicIntegrationGerenciappPaymentRouteImport.update({
    id: '/api/public/integration/gerenciapp/payment',
    path: '/api/public/integration/gerenciapp/payment',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/kits': typeof KitsRoute
  '/manutencao': typeof ManutencaoRoute
  '/monte-seu-kit': typeof MonteSeuKitRoute
  '/pocoes': typeof PocoesRoute
  '/sobre': typeof SobreRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/depoimentos': typeof AdminDepoimentosRoute
  '/admin/destaques': typeof AdminDestaquesRoute
  '/admin/jornada': typeof AdminJornadaRoute
  '/admin/kits': typeof AdminKitsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/api/audit-manual': typeof ApiAuditManualRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/hooks/stock-zero': typeof ApiPublicHooksStockZeroRoute
  '/api/public/integration/gerenciapp/payment': typeof ApiPublicIntegrationGerenciappPaymentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/kits': typeof KitsRoute
  '/manutencao': typeof ManutencaoRoute
  '/monte-seu-kit': typeof MonteSeuKitRoute
  '/pocoes': typeof PocoesRoute
  '/sobre': typeof SobreRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/depoimentos': typeof AdminDepoimentosRoute
  '/admin/destaques': typeof AdminDestaquesRoute
  '/admin/jornada': typeof AdminJornadaRoute
  '/admin/kits': typeof AdminKitsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/api/audit-manual': typeof ApiAuditManualRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/hooks/stock-zero': typeof ApiPublicHooksStockZeroRoute
  '/api/public/integration/gerenciapp/payment': typeof ApiPublicIntegrationGerenciappPaymentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/kits': typeof KitsRoute
  '/manutencao': typeof ManutencaoRoute
  '/monte-seu-kit': typeof MonteSeuKitRoute
  '/pocoes': typeof PocoesRoute
  '/sobre': typeof SobreRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/depoimentos': typeof AdminDepoimentosRoute
  '/admin/destaques': typeof AdminDestaquesRoute
  '/admin/jornada': typeof AdminJornadaRoute
  '/admin/kits': typeof AdminKitsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/api/audit-manual': typeof ApiAuditManualRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/hooks/stock-zero': typeof ApiPublicHooksStockZeroRoute
  '/api/public/integration/gerenciapp/payment': typeof ApiPublicIntegrationGerenciappPaymentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/kits'
    | '/manutencao'
    | '/monte-seu-kit'
    | '/pocoes'
    | '/sobre'
    | '/admin/backup'
    | '/admin/depoimentos'
    | '/admin/destaques'
    | '/admin/jornada'
    | '/admin/kits'
    | '/admin/login'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/api/audit-manual'
    | '/admin/'
    | '/api/public/hooks/stock-zero'
    | '/api/public/integration/gerenciapp/payment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/kits'
    | '/manutencao'
    | '/monte-seu-kit'
    | '/pocoes'
    | '/sobre'
    | '/admin/backup'
    | '/admin/depoimentos'
    | '/admin/destaques'
    | '/admin/jornada'
    | '/admin/kits'
    | '/admin/login'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/api/audit-manual'
    | '/admin'
    | '/api/public/hooks/stock-zero'
    | '/api/public/integration/gerenciapp/payment'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/kits'
    | '/manutencao'
    | '/monte-seu-kit'
    | '/pocoes'
    | '/sobre'
    | '/admin/backup'
    | '/admin/depoimentos'
    | '/admin/destaques'
    | '/admin/jornada'
    | '/admin/kits'
    | '/admin/login'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/api/audit-manual'
    | '/admin/'
    | '/api/public/hooks/stock-zero'
    | '/api/public/integration/gerenciapp/payment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  KitsRoute: typeof KitsRoute
  ManutencaoRoute: typeof ManutencaoRoute
  MonteSeuKitRoute: typeof MonteSeuKitRoute
  PocoesRoute: typeof PocoesRoute
  SobreRoute: typeof SobreRoute
  AdminBackupRoute: typeof AdminBackupRoute
  AdminDepoimentosRoute: typeof AdminDepoimentosRoute
  AdminDestaquesRoute: typeof AdminDestaquesRoute
  AdminJornadaRoute: typeof AdminJornadaRoute
  AdminKitsRoute: typeof AdminKitsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  ApiAuditManualRoute: typeof ApiAuditManualRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiPublicHooksStockZeroRoute: typeof ApiPublicHooksStockZeroRoute
  ApiPublicIntegrationGerenciappPaymentRoute: typeof ApiPublicIntegrationGerenciappPaymentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pocoes': {
      id: '/pocoes'
      path: '/pocoes'
      fullPath: '/pocoes'
      preLoaderRoute: typeof PocoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monte-seu-kit': {
      id: '/monte-seu-kit'
      path: '/monte-seu-kit'
      fullPath: '/monte-seu-kit'
      preLoaderRoute: typeof MonteSeuKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manutencao': {
      id: '/manutencao'
      path: '/manutencao'
      fullPath: '/manutencao'
      preLoaderRoute: typeof ManutencaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kits': {
      id: '/kits'
      path: '/kits'
      fullPath: '/kits'
      preLoaderRoute: typeof KitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audit-manual': {
      id: '/api/audit-manual'
      path: '/api/audit-manual'
      fullPath: '/api/audit-manual'
      preLoaderRoute: typeof ApiAuditManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/admin/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/admin/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kits': {
      id: '/admin/kits'
      path: '/admin/kits'
      fullPath: '/admin/kits'
      preLoaderRoute: typeof AdminKitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jornada': {
      id: '/admin/jornada'
      path: '/admin/jornada'
      fullPath: '/admin/jornada'
      preLoaderRoute: typeof AdminJornadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/destaques': {
      id: '/admin/destaques'
      path: '/admin/destaques'
      fullPath: '/admin/destaques'
      preLoaderRoute: typeof AdminDestaquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/depoimentos': {
      id: '/admin/depoimentos'
      path: '/admin/depoimentos'
      fullPath: '/admin/depoimentos'
      preLoaderRoute: typeof AdminDepoimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/backup': {
      id: '/admin/backup'
      path: '/admin/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AdminBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/stock-zero': {
      id: '/api/public/hooks/stock-zero'
      path: '/api/public/hooks/stock-zero'
      fullPath: '/api/public/hooks/stock-zero'
      preLoaderRoute: typeof ApiPublicHooksStockZeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/integration/gerenciapp/payment': {
      id: '/api/public/integration/gerenciapp/payment'
      path: '/api/public/integration/gerenciapp/payment'
      fullPath: '/api/public/integration/gerenciapp/payment'
      preLoaderRoute: typeof ApiPublicIntegrationGerenciappPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  KitsRoute: KitsRoute,
  ManutencaoRoute: ManutencaoRoute,
  MonteSeuKitRoute: MonteSeuKitRoute,
  PocoesRoute: PocoesRoute,
  SobreRoute: SobreRoute,
  AdminBackupRoute: AdminBackupRoute,
  AdminDepoimentosRoute: AdminDepoimentosRoute,
  AdminDestaquesRoute: AdminDestaquesRoute,
  AdminJornadaRoute: AdminJornadaRoute,
  AdminKitsRoute: AdminKitsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  ApiAuditManualRoute: ApiAuditManualRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiPublicHooksStockZeroRoute: ApiPublicHooksStockZeroRoute,
  ApiPublicIntegrationGerenciappPaymentRoute:
    ApiPublicIntegrationGerenciappPaymentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
