// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = "https://crsjmyrkbpawxqgvfmrv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNyc2pteXJrYnBhd3hxZ3ZmbXJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU5ODA5MzEsImV4cCI6MjEwMTU1NjkzMX0.sSZYBvyoPiQgVSBSKThee6_Pvhp41NJ_ioZf2JF_ado";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});